network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
  bridges:
    br0:
      interfaces: [ eth0 ]
      dhcp4: false
      dhcp6: false
      addresses: [192.168.1.68/24]
      gateway4: 192.168.1.1
      nameservers:
        addresses: [192.168.1.1]