#!/bin/bash
pushd /home/sean/go/src/github.com/sean-jc/intel_sgx
# sudo -E systemctl stop aesmd &
sudo -E rmmod sgx 
set -e
#Ensure the driver module was removed
! ls /dev/sgx
if ! git diff --quiet ; then
    git stash save
    git cherry-pick --no-commit 4ee673e 5ee0823 b57426e
    git stash pop
else
    git cherry-pick --no-commit 4ee673e 5ee0823 b57426e
fi
sudo -E make clean
sudo -E make
sudo -E insmod sgx.ko
ls /dev/sgx
popd
