#!/bin/bash
cd /opt/intel
sudo -E sgxsdk/uninstall.sh
sudo -E sgxpsw/uninstall.sh
cd - > /dev/null
rm -rf /home/sean/go/src/github.com/sean-jc/engarde/sdk
set -e
cd /home/sean/go/src/github.com/01org/linux-sgx
make
make psw_install_pkg
make sdk_install_pkg
cd /opt/intel
sudo -E /home/sean/go/src/github.com/01org/linux-sgx/linux/installer/bin/sgx_linux_x64_psw_1.*.bin
sudo -E sh -c 'echo yes | /home/sean/go/src/github.com/01org/linux-sgx/linux/installer/bin/sgx_linux_x64_sdk_1.*.bin'
cd - > /dev/null
mkdir /home/sean/go/src/github.com/sean-jc/engarde/sdk
cp -R /opt/intel/sgxsdk/bin /home/sean/go/src/github.com/sean-jc/engarde/sdk/
cp -R /opt/intel/sgxsdk/include /home/sean/go/src/github.com/sean-jc/engarde/sdk/
cp -R /opt/intel/sgxsdk/lib64 /home/sean/go/src/github.com/sean-jc/engarde/sdk/
