#!/bin/bash
. $SETTINGS/bash/apt
. $SETTINGS/bash/utils

#
function install-qemu-deps() {
	ad
	ai libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev libaio-dev libbrlapi-dev libbz2-dev libcap-dev libcap-ng-dev libcurl4-gnutls-dev libncurses5-dev libsnappy-dev libssh2-1-dev liblzo2-dev libsasl2-dev libvdeplug-dev

	# Old
	# libcurl3 libjpeg8-dev

	# New
	ai libcurl4 libjpeg9-dev

}

function configure-qemu() {
	$HOME/go/src/github.com/qemu/qemu/configure --target-list=x86_64-softmmu --static \
	--without-default-features \
	--enable-attr \
	--enable-kvm \
	--enable-malloc-trim \
	--enable-membarrier \
	--enable-multiprocess \
	--enable-qcow1 \
	--enable-virtfs \
	--enable-vhost-kernel \
	--enable-vhost-net \
	--enable-vhost-user \
	--enable-vnc \
	--enable-vvfat \
	--enable-werror \
	--enable-zstd \
	--firmwarepath=pc-bios \
	--disable-alsa \
	--disable-auth-pam \
	--disable-bochs \
	--disable-brlapi \
	--disable-capstone \
	--disable-cloop \
	--disable-coreaudio \
	--disable-crypto-afalg \
	--disable-curl \
	--disable-curses \
	--disable-debug-mutex \
	--disable-dmg \
	--disable-docs \
	--disable-dsound \
	--disable-fdt \
	--disable-fuzzing \
	--disable-gettext \
	--disable-glusterfs \
	--disable-gnutls \
	--disable-guest-agent \
	--disable-guest-agent-msi \
	--disable-gcrypt \
	--disable-gtk \
	--disable-hvf \
	--disable-jack \
	--disable-install-blobs \
	--disable-libnfs \
	--disable-libusb \
	--disable-libssh \
	--disable-modules \
	--disable-netmap \
	--disable-nettle \
	--disable-numa \
	--disable-opengl \
	--disable-oss \
	--disable-pa \
	--disable-parallels \
	--disable-qed \
	--disable-qga-vss \
	--disable-qom-cast-debug \
	--disable-rbd \
	--disable-rdma \
	--disable-replication \
	--disable-sdl \
	--disable-selinux \
	--disable-smartcard \
	--disable-sparse \
	--disable-spice \
	--disable-tcg \
	--disable-tools \
	--disable-tpm \
	--disable-usb-redir \
	--disable-vde \
	--disable-vdi \
	--disable-virglrenderer \
	--disable-vnc \
	--disable-vnc-sasl \
	--disable-vte \
	--disable-xen \
	--disable-xen-pci-passthrough \
	--disable-whpx \
	--audio-drv-list=
}

function qemu-copy-firmware() {
	local build=$(pwd | rev | cut -d'/' -f1 | rev)
	local dir="$HOME/Downloads/$build/pc-bios"

	mkdir -p $dir

	pushd $HOME/go/src/github.com/qemu/qemu
	cp $(find . -name bios-256k.bin) $dir
	cp $(find . -name bios.bin) $dir
	cp -r $(find . -name keymaps) $dir
	cp $(find . -name kvmvapic.bin) $dir
	cp $(find . -name linuxboot.bin) $dir
	cp $(find . -name linuxboot_dma.bin) $dir
	cp $(find . -name multiboot.bin) $dir
	cp $(find . -name multiboot_dma.bin) $dir
	popd
}
alias pq='package-qemu'
